name = "journal-calendar"
main = "src/index.ts"
compatibility_date = "2026-05-01"

[[kv_namespaces]]
binding = "JOURNAL"
id = "e329d26f945e46c094a7bf982d8a5895"

[vars]
ALLOWED_ORIGIN = "https://lumineks.github.io"

[env.dev]
[env.dev.vars]
ALLOWED_ORIGIN = "http://localhost:5173"

[[env.dev.kv_namespaces]]
binding = "JOURNAL"
id = "6e25ab0cda1344f793f2c7872e54a19b"
